"""Add original_query column to Claim model

Revision ID: 0b4eb2fc42ef
Revises: 450ba8ec753e
Create Date: 2024-10-22 23:38:09.105696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4eb2fc42ef'
down_revision = '450ba8ec753e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_query', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_column('original_query')

    # ### end Alembic commands ###
