"""Add veracity assessment and intentionality categorization

Revision ID: 450ba8ec753e
Revises: 
Create Date: 2024-09-27 01:16:54.519876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450ba8ec753e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('veracity_probability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('veracity_justification', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('final_truth_score', sa.Float(), nullable=True))

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intent_category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('intent_explanation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('intent_explanation')
        batch_op.drop_column('intent_category')

    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_column('final_truth_score')
        batch_op.drop_column('veracity_justification')
        batch_op.drop_column('veracity_probability')

    # ### end Alembic commands ###
