"""Add original_query column to Claim model

Revision ID: fe028f43d6e9
Revises: 450ba8ec753e
Create Date: 2024-10-22 23:23:53.569123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe028f43d6e9'
down_revision = '450ba8ec753e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_query', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_column('original_query')

    # ### end Alembic commands ###
